apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotto-app
  template:
    metadata:
      labels:
        app: lotto-app
    spec:
      containers:
        - name: lotto-app
          image: your-dockerhub-username/lotto-app:latest  # Replace with your actual image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/lotto_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
